// autogenerated by @jersey/openapi
import type { operations } from './schema.ts';
/** Automatically generated route definitions based on the OpenAPI schema */
export type routes =
	| {
		method: 'post';
		path: `/channels/${string}/messages`;
		parts: 3;
		params: operations['ChannelMessageCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ChannelMessageCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/messages';
		parts: 3;
		params: operations['ChannelMessageCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ChannelMessageCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/messages`;
		parts: 3;
		params: operations['ChannelMessageReadMany']['parameters']['query'];
		response:
			operations['ChannelMessageReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/messages';
		parts: 3;
		params: operations['ChannelMessageReadMany']['parameters']['query'];
		response:
			operations['ChannelMessageReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/messages/${string}`;
		parts: 4;
		params: undefined;
		response: operations['ChannelMessageRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/messages/{messageId}';
		parts: 4;
		params: undefined;
		response: operations['ChannelMessageRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/channels/${string}/messages/${string}`;
		parts: 4;
		params: operations['ChannelMessageUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ChannelMessageUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/messages/{messageId}';
		parts: 4;
		params: operations['ChannelMessageUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ChannelMessageUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/messages/{messageId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/groups/${string}/members/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/groups/{groupId}/members/{userId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/groups/${string}/members/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/groups/{groupId}/members/{userId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/servers/${string}/members/${string}/xp`;
		parts: 5;
		params: operations['ServerXpForUserCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/members/{userId}/xp';
		parts: 5;
		params: operations['ServerXpForUserCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: `/servers/${string}/members/${string}/xp`;
		parts: 5;
		params: operations['ServerXpForUserUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: '-/servers/{serverId}/members/{userId}/xp';
		parts: 5;
		params: operations['ServerXpForUserUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/servers/${string}/xp`;
		parts: 3;
		params: operations['ServerXpForUserCreateMany']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserCreateMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/xp';
		parts: 3;
		params: operations['ServerXpForUserCreateMany']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserCreateMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: `/servers/${string}/xp`;
		parts: 3;
		params: operations['ServerXpForUserUpdateMany']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserUpdateMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: '-/servers/{serverId}/xp';
		parts: 3;
		params: operations['ServerXpForUserUpdateMany']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerXpForUserUpdateMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/servers/${string}/roles/${string}/xp`;
		parts: 5;
		params: operations['ServerXpForRoleCreate']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/roles/{roleId}/xp';
		parts: 5;
		params: operations['ServerXpForRoleCreate']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'put';
		path: `/servers/${string}/members/${string}/roles/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/servers/{serverId}/members/{userId}/roles/{roleId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/servers/${string}/members/${string}/roles/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/members/{userId}/roles/{roleId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/members/${string}/roles`;
		parts: 5;
		params: undefined;
		response:
			operations['RoleMembershipReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/members/{userId}/roles';
		parts: 5;
		params: undefined;
		response:
			operations['RoleMembershipReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/channels/${string}/topics`;
		parts: 3;
		params: operations['ForumTopicCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ForumTopicCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/topics';
		parts: 3;
		params: operations['ForumTopicCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ForumTopicCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/topics`;
		parts: 3;
		params: operations['ForumTopicReadMany']['parameters']['query'];
		response: operations['ForumTopicReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/topics';
		parts: 3;
		params: operations['ForumTopicReadMany']['parameters']['query'];
		response: operations['ForumTopicReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/topics/${string}`;
		parts: 4;
		params: undefined;
		response: operations['ForumTopicRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/topics/{forumTopicId}';
		parts: 4;
		params: undefined;
		response: operations['ForumTopicRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/topics/${string}`;
		parts: 4;
		params: operations['ForumTopicUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ForumTopicUpdate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}/topics/{forumTopicId}';
		parts: 4;
		params: operations['ForumTopicUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ForumTopicUpdate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/topics/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/topics/{forumTopicId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/channels/${string}/topics/${string}/pin`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/topics/{forumTopicId}/pin';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/topics/${string}/pin`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/topics/{forumTopicId}/pin';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/channels/${string}/topics/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/topics/{forumTopicId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/topics/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/topics/{forumTopicId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/channels/${string}/topics/${string}/lock`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/topics/{forumTopicId}/lock';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/topics/${string}/lock`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/topics/{forumTopicId}/lock';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/topics/${string}/comments`;
		parts: 5;
		params: operations['ForumTopicCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ForumTopicCommentCreate']['responses']['201']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/topics/{forumTopicId}/comments';
		parts: 5;
		params: operations['ForumTopicCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ForumTopicCommentCreate']['responses']['201']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/topics/${string}/comments`;
		parts: 5;
		params: undefined;
		response:
			operations['ForumTopicCommentReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/topics/{forumTopicId}/comments';
		parts: 5;
		params: undefined;
		response:
			operations['ForumTopicCommentReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/topics/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response:
			operations['ForumTopicCommentRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path:
			'-/channels/{channelId}/topics/{forumTopicId}/comments/{forumTopicCommentId}';
		parts: 6;
		params: undefined;
		response:
			operations['ForumTopicCommentRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/topics/${string}/comments/${string}`;
		parts: 6;
		params: operations['ForumTopicCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ForumTopicCommentUpdate']['responses']['201']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path:
			'-/channels/{channelId}/topics/{forumTopicId}/comments/{forumTopicCommentId}';
		parts: 6;
		params: operations['ForumTopicCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ForumTopicCommentUpdate']['responses']['201']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/topics/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/topics/{forumTopicId}/comments/{forumTopicCommentId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/items`;
		parts: 3;
		params: operations['ListItemCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ListItemCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/items';
		parts: 3;
		params: operations['ListItemCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ListItemCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/items`;
		parts: 3;
		params: undefined;
		response: operations['ListItemReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/items';
		parts: 3;
		params: undefined;
		response: operations['ListItemReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/items/${string}`;
		parts: 4;
		params: undefined;
		response: operations['ListItemRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/items/{listItemId}';
		parts: 4;
		params: undefined;
		response: operations['ListItemRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/items/${string}`;
		parts: 4;
		params: operations['ListItemUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ListItemUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}/items/{listItemId}';
		parts: 4;
		params: operations['ListItemUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['ListItemUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/items/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/items/{listItemId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/items/${string}/complete`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/items/{listItemId}/complete';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/items/${string}/complete`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/items/{listItemId}/complete';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/members/${string}/social-links/${string}`;
		parts: 6;
		params: undefined;
		response: operations['MemberSocialLinkRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/members/{userId}/social-links/{socialLinkType}';
		parts: 6;
		params: undefined;
		response: operations['MemberSocialLinkRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/servers/${string}/members/${string}/nickname`;
		parts: 5;
		params: operations['MemberNicknameUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['MemberNicknameUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/servers/{serverId}/members/{userId}/nickname';
		parts: 5;
		params: operations['MemberNicknameUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['MemberNicknameUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/members/${string}/nickname`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/members/{userId}/nickname';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels`;
		parts: 1;
		params:
			operations['ChannelCreate']['requestBody']['content']['application/json'];
		response: operations['ChannelCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}`;
		parts: 2;
		params: undefined;
		response: operations['ChannelRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}';
		parts: 2;
		params: undefined;
		response: operations['ChannelRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/channels/${string}`;
		parts: 2;
		params:
			operations['ChannelUpdate']['requestBody']['content']['application/json'];
		response: operations['ChannelUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}';
		parts: 2;
		params:
			operations['ChannelUpdate']['requestBody']['content']['application/json'];
		response: operations['ChannelUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}`;
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}';
		parts: 2;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/docs`;
		parts: 3;
		params:
			operations['DocCreate']['requestBody']['content']['application/json'];
		response: operations['DocCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/docs';
		parts: 3;
		params:
			operations['DocCreate']['requestBody']['content']['application/json'];
		response: operations['DocCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/docs`;
		parts: 3;
		params: operations['DocReadMany']['parameters']['query'];
		response: operations['DocReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/docs';
		parts: 3;
		params: operations['DocReadMany']['parameters']['query'];
		response: operations['DocReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/docs/${string}`;
		parts: 4;
		params: undefined;
		response:
			operations['DocRead']['responses']['200']['content']['application/json'];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/docs/{docId}';
		parts: 4;
		params: undefined;
		response:
			operations['DocRead']['responses']['200']['content']['application/json'];
	}
	| {
		method: 'put';
		path: `/channels/${string}/docs/${string}`;
		parts: 4;
		params:
			operations['DocUpdate']['requestBody']['content']['application/json'];
		response: operations['DocUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/docs/{docId}';
		parts: 4;
		params:
			operations['DocUpdate']['requestBody']['content']['application/json'];
		response: operations['DocUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/docs/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/docs/{docId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/members/${string}`;
		parts: 4;
		params: undefined;
		response: operations['ServerMemberRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/members/{userId}';
		parts: 4;
		params: undefined;
		response: operations['ServerMemberRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/members/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/members/{userId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/members`;
		parts: 3;
		params: undefined;
		response: operations['ServerMemberReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/members';
		parts: 3;
		params: undefined;
		response: operations['ServerMemberReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/servers/${string}/bans/${string}`;
		parts: 4;
		params: operations['ServerMemberBanCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerMemberBanCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/bans/{userId}';
		parts: 4;
		params: operations['ServerMemberBanCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ServerMemberBanCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/servers/${string}/bans/${string}`;
		parts: 4;
		params: undefined;
		response: operations['ServerMemberBanRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/bans/{userId}';
		parts: 4;
		params: undefined;
		response: operations['ServerMemberBanRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/bans/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/bans/{userId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/bans`;
		parts: 3;
		params: undefined;
		response:
			operations['ServerMemberBanReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/bans';
		parts: 3;
		params: undefined;
		response:
			operations['ServerMemberBanReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: `/servers/${string}/webhooks`;
		parts: 3;
		params:
			operations['WebhookCreate']['requestBody']['content']['application/json'];
		response: operations['WebhookCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/webhooks';
		parts: 3;
		params:
			operations['WebhookCreate']['requestBody']['content']['application/json'];
		response: operations['WebhookCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/webhooks`;
		parts: 3;
		params: operations['WebhookReadMany']['parameters']['query'];
		response: operations['WebhookReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/webhooks';
		parts: 3;
		params: operations['WebhookReadMany']['parameters']['query'];
		response: operations['WebhookReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/webhooks/${string}`;
		parts: 4;
		params: undefined;
		response: operations['WebhookRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/webhooks/{webhookId}';
		parts: 4;
		params: undefined;
		response: operations['WebhookRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/servers/${string}/webhooks/${string}`;
		parts: 4;
		params:
			operations['WebhookUpdate']['requestBody']['content']['application/json'];
		response: operations['WebhookUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: '-/servers/{serverId}/webhooks/{webhookId}';
		parts: 4;
		params:
			operations['WebhookUpdate']['requestBody']['content']['application/json'];
		response: operations['WebhookUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/webhooks/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/webhooks/{webhookId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}`;
		parts: 2;
		params: undefined;
		response: operations['ServerRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}';
		parts: 2;
		params: undefined;
		response: operations['ServerRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/channels/${string}/events`;
		parts: 3;
		params: operations['CalendarEventCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CalendarEventCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/events';
		parts: 3;
		params: operations['CalendarEventCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CalendarEventCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/events`;
		parts: 3;
		params: operations['CalendarEventReadMany']['parameters']['query'];
		response:
			operations['CalendarEventReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/events';
		parts: 3;
		params: operations['CalendarEventReadMany']['parameters']['query'];
		response:
			operations['CalendarEventReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/events/${string}`;
		parts: 4;
		params: undefined;
		response: operations['CalendarEventRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/events/{calendarEventId}';
		parts: 4;
		params: undefined;
		response: operations['CalendarEventRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/events/${string}`;
		parts: 4;
		params: operations['CalendarEventUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CalendarEventUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}/events/{calendarEventId}';
		parts: 4;
		params: operations['CalendarEventUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CalendarEventUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/events/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/events/{calendarEventId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/channels/${string}/events/${string}/rsvps/${string}`;
		parts: 6;
		params: undefined;
		response:
			operations['CalendarEventRsvpRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/events/{calendarEventId}/rsvps/{userId}';
		parts: 6;
		params: undefined;
		response:
			operations['CalendarEventRsvpRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: `/channels/${string}/events/${string}/rsvps/${string}`;
		parts: 6;
		params: operations['CalendarEventRsvpUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['CalendarEventRsvpUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/events/{calendarEventId}/rsvps/{userId}';
		parts: 6;
		params: operations['CalendarEventRsvpUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['CalendarEventRsvpUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/events/${string}/rsvps/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/events/{calendarEventId}/rsvps/{userId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/channels/${string}/events/${string}/rsvps`;
		parts: 5;
		params: undefined;
		response:
			operations['CalendarEventRsvpReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/events/{calendarEventId}/rsvps';
		parts: 5;
		params: undefined;
		response:
			operations['CalendarEventRsvpReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: `/channels/${string}/events/${string}/rsvps`;
		parts: 5;
		params: operations['CalendarEventRsvpUpdateMany']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/events/{calendarEventId}/rsvps';
		parts: 5;
		params: operations['CalendarEventRsvpUpdateMany']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'get';
		path: `/users/${string}`;
		parts: 2;
		params: undefined;
		response:
			operations['UserRead']['responses']['200']['content']['application/json'];
	}
	| {
		method: 'get';
		path: '-/users/{userId}';
		parts: 2;
		params: undefined;
		response:
			operations['UserRead']['responses']['200']['content']['application/json'];
	}
	| {
		method: 'put';
		path:
			`/channels/${string}/topics/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			'-/channels/{channelId}/topics/{forumTopicId}/comments/{forumTopicCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			`/channels/${string}/topics/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/topics/{forumTopicId}/comments/{forumTopicCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/events/${string}/comments`;
		parts: 5;
		params: operations['CalendarEventCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['CalendarEventCommentCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/events/{calendarEventId}/comments';
		parts: 5;
		params: operations['CalendarEventCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['CalendarEventCommentCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/events/${string}/comments`;
		parts: 5;
		params: undefined;
		response:
			operations['CalendarEventCommentReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/events/{calendarEventId}/comments';
		parts: 5;
		params: undefined;
		response:
			operations['CalendarEventCommentReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/events/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response:
			operations['CalendarEventCommentRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path:
			'-/channels/{channelId}/events/{calendarEventId}/comments/{calendarEventCommentId}';
		parts: 6;
		params: undefined;
		response:
			operations['CalendarEventCommentRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/events/${string}/comments/${string}`;
		parts: 6;
		params: operations['CalendarEventCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['CalendarEventCommentUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path:
			'-/channels/{channelId}/events/{calendarEventId}/comments/{calendarEventCommentId}';
		parts: 6;
		params: operations['CalendarEventCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['CalendarEventCommentUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/events/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/events/{calendarEventId}/comments/{calendarEventCommentId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/channels/${string}/events/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/events/{calendarEventId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/events/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/events/{calendarEventId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			`/channels/${string}/events/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			'-/channels/{channelId}/events/{calendarEventId}/comments/{calendarEventCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			`/channels/${string}/events/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/events/{calendarEventId}/comments/{calendarEventCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/docs/${string}/comments`;
		parts: 5;
		params: operations['DocCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['DocCommentCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/docs/{docId}/comments';
		parts: 5;
		params: operations['DocCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['DocCommentCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/docs/${string}/comments`;
		parts: 5;
		params: undefined;
		response: operations['DocCommentReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/docs/{docId}/comments';
		parts: 5;
		params: undefined;
		response: operations['DocCommentReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/docs/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response: operations['DocCommentRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/docs/{docId}/comments/{docCommentId}';
		parts: 6;
		params: undefined;
		response: operations['DocCommentRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/docs/${string}/comments/${string}`;
		parts: 6;
		params: operations['DocCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['DocCommentUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}/docs/{docId}/comments/{docCommentId}';
		parts: 6;
		params: operations['DocCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['DocCommentUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/docs/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/docs/{docId}/comments/{docCommentId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/channels/${string}/docs/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/docs/{docId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/docs/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/docs/{docId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			`/channels/${string}/docs/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			'-/channels/{channelId}/docs/{docId}/comments/{docCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			`/channels/${string}/docs/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/docs/{docId}/comments/{docCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'patch';
		path: `/channels/${string}/event_series/${string}`;
		parts: 4;
		params: operations['CalendarEventSeriesUpdate']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}/event_series/{calendarEventSeriesId}';
		parts: 4;
		params: operations['CalendarEventSeriesUpdate']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/event_series/${string}`;
		parts: 4;
		params: operations['CalendarEventSeriesDelete']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/event_series/{calendarEventSeriesId}';
		parts: 4;
		params: operations['CalendarEventSeriesDelete']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/announcements`;
		parts: 3;
		params: operations['AnnouncementCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['AnnouncementCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/announcements';
		parts: 3;
		params: operations['AnnouncementCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['AnnouncementCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/announcements`;
		parts: 3;
		params: operations['AnnouncementReadMany']['parameters']['query'];
		response: operations['AnnouncementReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/announcements';
		parts: 3;
		params: operations['AnnouncementReadMany']['parameters']['query'];
		response: operations['AnnouncementReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/channels/${string}/announcements/${string}`;
		parts: 4;
		params: undefined;
		response: operations['AnnouncementRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/announcements/{announcementId}';
		parts: 4;
		params: undefined;
		response: operations['AnnouncementRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/announcements/${string}`;
		parts: 4;
		params: operations['AnnouncementUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['AnnouncementUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/channels/{channelId}/announcements/{announcementId}';
		parts: 4;
		params: operations['AnnouncementUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['AnnouncementUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/announcements/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/announcements/{announcementId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/users/${string}/servers`;
		parts: 3;
		params: undefined;
		response: operations['UserServerReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/users/{userId}/servers';
		parts: 3;
		params: undefined;
		response: operations['UserServerReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'put';
		path: `/channels/${string}/announcements/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/announcements/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/channels/${string}/announcements/${string}/comments`;
		parts: 5;
		params: operations['AnnouncementCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['AnnouncementCommentCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/announcements/{announcementId}/comments';
		parts: 5;
		params: operations['AnnouncementCommentCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['AnnouncementCommentCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/announcements/${string}/comments`;
		parts: 5;
		params: undefined;
		response:
			operations['AnnouncementCommentReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/channels/{channelId}/announcements/{announcementId}/comments';
		parts: 5;
		params: undefined;
		response:
			operations['AnnouncementCommentReadMany']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/channels/${string}/announcements/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response:
			operations['AnnouncementCommentRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/comments/{announcementCommentId}';
		parts: 6;
		params: undefined;
		response:
			operations['AnnouncementCommentRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path: `/channels/${string}/announcements/${string}/comments/${string}`;
		parts: 6;
		params: operations['AnnouncementCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['AnnouncementCommentUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/comments/{announcementCommentId}';
		parts: 6;
		params: operations['AnnouncementCommentUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['AnnouncementCommentUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/channels/${string}/announcements/${string}/comments/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/comments/{announcementCommentId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			`/channels/${string}/announcements/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/comments/{announcementCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			`/channels/${string}/announcements/${string}/comments/${string}/emotes/${string}`;
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/channels/{channelId}/announcements/{announcementId}/comments/{announcementCommentId}/emotes/{emoteId}';
		parts: 8;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/users/${string}/status`;
		parts: 3;
		params: operations['UserStatusCreate']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/users/{userId}/status';
		parts: 3;
		params: operations['UserStatusCreate']['requestBody']['content'][
			'application/json'
		];
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/users/${string}/status`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/users/{userId}/status';
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: `/channels/${string}/messages/${string}/emotes/${string}`;
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/messages/{messageId}/emotes/{emoteId}';
		parts: 6;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}/emotes/${string}`;
		parts: 6;
		params: operations['ChannelMessageReactionDelete']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/messages/{messageId}/emotes/{emoteId}';
		parts: 6;
		params: operations['ChannelMessageReactionDelete']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}/emotes`;
		parts: 5;
		params:
			operations['ChannelMessageReactionDeleteMany']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/messages/{messageId}/emotes';
		parts: 5;
		params:
			operations['ChannelMessageReactionDeleteMany']['parameters']['query'];
		response: undefined;
	}
	| {
		method: 'post';
		path: `/servers/${string}/groups`;
		parts: 3;
		params:
			operations['GroupCreate']['requestBody']['content']['application/json'];
		response: operations['GroupCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/groups';
		parts: 3;
		params:
			operations['GroupCreate']['requestBody']['content']['application/json'];
		response: operations['GroupCreate']['responses']['201']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/groups`;
		parts: 3;
		params: undefined;
		response: operations['GroupReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/groups';
		parts: 3;
		params: undefined;
		response: operations['GroupReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/groups/${string}`;
		parts: 4;
		params: undefined;
		response: operations['GroupRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/groups/{groupId}';
		parts: 4;
		params: undefined;
		response: operations['GroupRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/groups/${string}`;
		parts: 4;
		params:
			operations['GroupUpdate']['requestBody']['content']['application/json'];
		response: operations['GroupUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{serverId}/groups/{groupId}';
		parts: 4;
		params:
			operations['GroupUpdate']['requestBody']['content']['application/json'];
		response: operations['GroupUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/groups/${string}`;
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/groups/{groupId}';
		parts: 4;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/servers/${string}/roles`;
		parts: 3;
		params:
			operations['RoleCreate']['requestBody']['content']['application/json'];
		response: operations['RoleCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/roles';
		parts: 3;
		params:
			operations['RoleCreate']['requestBody']['content']['application/json'];
		response: operations['RoleCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/roles`;
		parts: 3;
		params: undefined;
		response: operations['RoleReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/roles';
		parts: 3;
		params: undefined;
		response: operations['RoleReadMany']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/roles/${string}`;
		parts: 4;
		params: undefined;
		response:
			operations['RoleRead']['responses']['200']['content']['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/roles/{roleId}';
		parts: 4;
		params: undefined;
		response:
			operations['RoleRead']['responses']['200']['content']['application/json'];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/roles/${string}`;
		parts: 4;
		params:
			operations['RoleUpdate']['requestBody']['content']['application/json'];
		response: operations['RoleUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{serverId}/roles/{roleId}';
		parts: 4;
		params:
			operations['RoleUpdate']['requestBody']['content']['application/json'];
		response: operations['RoleUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/roles/${string}`;
		parts: 4;
		params: undefined;
		response: operations['RoleDelete']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/roles/{roleId}';
		parts: 4;
		params: undefined;
		response: operations['RoleDelete']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/roles/${string}/permissions`;
		parts: 5;
		params: operations['RolePermissionUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['RolePermissionUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{serverId}/roles/{roleId}/permissions';
		parts: 5;
		params: operations['RolePermissionUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['RolePermissionUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/subscriptions/tiers/${string}`;
		parts: 5;
		params: undefined;
		response:
			operations['ServerSubscriptionTierRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path:
			'-/servers/{serverId}/subscriptions/tiers/{serverSubscriptionTierType}';
		parts: 5;
		params: undefined;
		response:
			operations['ServerSubscriptionTierRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/servers/${string}/subscriptions/tiers`;
		parts: 4;
		params: undefined;
		response: operations['ServerSubscriptionTierReadMany']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/subscriptions/tiers';
		parts: 4;
		params: undefined;
		response: operations['ServerSubscriptionTierReadMany']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: `/servers/${string}/members/${string}/permissions`;
		parts: 5;
		params: operations['ServerMemberPermissionsRead']['parameters']['query'];
		response:
			operations['ServerMemberPermissionsRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/members/{userId}/permissions';
		parts: 5;
		params: operations['ServerMemberPermissionsRead']['parameters']['query'];
		response:
			operations['ServerMemberPermissionsRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'put';
		path: `/channels/${string}/archive`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'put';
		path: '-/channels/{channelId}/archive';
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/archive`;
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/archive';
		parts: 3;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/servers/${string}/categories`;
		parts: 3;
		params: operations['CategoryCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CategoryCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: '-/servers/{serverId}/categories';
		parts: 3;
		params: operations['CategoryCreate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CategoryCreate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: `/servers/${string}/categories/${string}`;
		parts: 4;
		params: undefined;
		response: operations['CategoryRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/categories/{categoryId}';
		parts: 4;
		params: undefined;
		response: operations['CategoryRead']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/categories/${string}`;
		parts: 4;
		params: operations['CategoryUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CategoryUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'patch';
		path: '-/servers/{serverId}/categories/{categoryId}';
		parts: 4;
		params: operations['CategoryUpdate']['requestBody']['content'][
			'application/json'
		];
		response: operations['CategoryUpdate']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/categories/${string}`;
		parts: 4;
		params: undefined;
		response: operations['CategoryDelete']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'delete';
		path: '-/servers/{serverId}/categories/{categoryId}';
		parts: 4;
		params: undefined;
		response: operations['CategoryDelete']['responses']['200']['content'][
			'application/json'
		];
	}
	| {
		method: 'post';
		path: `/channels/${string}/messages/${string}/pin`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: '-/channels/{channelId}/messages/{messageId}/pin';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: `/channels/${string}/messages/${string}/pin`;
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path: '-/channels/{channelId}/messages/{messageId}/pin';
		parts: 5;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'post';
		path: `/servers/${string}/channels/${string}/permissions/roles/${string}`;
		parts: 7;
		params: operations['ChannelRolePermissionCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelRolePermissionCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/roles/{roleId}';
		parts: 7;
		params: operations['ChannelRolePermissionCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelRolePermissionCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/servers/${string}/channels/${string}/permissions/roles/${string}`;
		parts: 7;
		params: undefined;
		response:
			operations['ChannelRolePermissionRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/roles/{roleId}';
		parts: 7;
		params: undefined;
		response:
			operations['ChannelRolePermissionRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/channels/${string}/permissions/roles/${string}`;
		parts: 7;
		params: operations['ChannelRolePermissionUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelRolePermissionUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/roles/{roleId}';
		parts: 7;
		params: operations['ChannelRolePermissionUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelRolePermissionUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/channels/${string}/permissions/roles/${string}`;
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/roles/{roleId}';
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/channels/${string}/permissions/roles`;
		parts: 6;
		params: undefined;
		response: operations['ChannelRolePermissionReadMany']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/channels/{channelId}/permissions/roles';
		parts: 6;
		params: undefined;
		response: operations['ChannelRolePermissionReadMany']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'post';
		path: `/servers/${string}/channels/${string}/permissions/users/${string}`;
		parts: 7;
		params: operations['ChannelUserPermissionCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelUserPermissionCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'post';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/users/{userId}';
		parts: 7;
		params: operations['ChannelUserPermissionCreate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelUserPermissionCreate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path: `/servers/${string}/channels/${string}/permissions/users/${string}`;
		parts: 7;
		params: undefined;
		response:
			operations['ChannelUserPermissionRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'get';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/users/{userId}';
		parts: 7;
		params: undefined;
		response:
			operations['ChannelUserPermissionRead']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/channels/${string}/permissions/users/${string}`;
		parts: 7;
		params: operations['ChannelUserPermissionUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelUserPermissionUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'patch';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/users/{userId}';
		parts: 7;
		params: operations['ChannelUserPermissionUpdate']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['ChannelUserPermissionUpdate']['responses']['200']['content'][
				'application/json'
			];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/channels/${string}/permissions/users/${string}`;
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/servers/{serverId}/channels/{channelId}/permissions/users/{userId}';
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/channels/${string}/permissions/users`;
		parts: 6;
		params: undefined;
		response: operations['ChannelUserPermissionReadMany']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/channels/{channelId}/permissions/users';
		parts: 6;
		params: undefined;
		response: operations['ChannelUserPermissionReadMany']['responses']['200'][
			'content'
		]['application/json'];
	}
	| {
		method: 'post';
		path: `/servers/${string}/categories/${string}/permissions/users/${string}`;
		parts: 7;
		params: operations['ChannelCategoryUserPermissionCreate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryUserPermissionCreate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/users/{userId}';
		parts: 7;
		params: operations['ChannelCategoryUserPermissionCreate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryUserPermissionCreate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: `/servers/${string}/categories/${string}/permissions/users/${string}`;
		parts: 7;
		params: undefined;
		response:
			operations['ChannelCategoryUserPermissionRead']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/users/{userId}';
		parts: 7;
		params: undefined;
		response:
			operations['ChannelCategoryUserPermissionRead']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/categories/${string}/permissions/users/${string}`;
		parts: 7;
		params: operations['ChannelCategoryUserPermissionUpdate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryUserPermissionUpdate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'patch';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/users/{userId}';
		parts: 7;
		params: operations['ChannelCategoryUserPermissionUpdate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryUserPermissionUpdate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/categories/${string}/permissions/users/${string}`;
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/users/{userId}';
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/categories/${string}/permissions/users`;
		parts: 6;
		params: undefined;
		response:
			operations['ChannelCategoryUserPermissionReadMany']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/categories/{categoryId}/permissions/users';
		parts: 6;
		params: undefined;
		response:
			operations['ChannelCategoryUserPermissionReadMany']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path: `/servers/${string}/categories/${string}/permissions/roles/${string}`;
		parts: 7;
		params: operations['ChannelCategoryRolePermissionCreate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryRolePermissionCreate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/roles/{roleId}';
		parts: 7;
		params: operations['ChannelCategoryRolePermissionCreate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryRolePermissionCreate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: `/servers/${string}/categories/${string}/permissions/roles/${string}`;
		parts: 7;
		params: undefined;
		response:
			operations['ChannelCategoryRolePermissionRead']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/roles/{roleId}';
		parts: 7;
		params: undefined;
		response:
			operations['ChannelCategoryRolePermissionRead']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'patch';
		path: `/servers/${string}/categories/${string}/permissions/roles/${string}`;
		parts: 7;
		params: operations['ChannelCategoryRolePermissionUpdate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryRolePermissionUpdate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'patch';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/roles/{roleId}';
		parts: 7;
		params: operations['ChannelCategoryRolePermissionUpdate']['requestBody'][
			'content'
		]['application/json'];
		response:
			operations['ChannelCategoryRolePermissionUpdate']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'delete';
		path: `/servers/${string}/categories/${string}/permissions/roles/${string}`;
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'delete';
		path:
			'-/servers/{serverId}/categories/{categoryId}/permissions/roles/{roleId}';
		parts: 7;
		params: undefined;
		response: undefined;
	}
	| {
		method: 'get';
		path: `/servers/${string}/categories/${string}/permissions/roles`;
		parts: 6;
		params: undefined;
		response:
			operations['ChannelCategoryRolePermissionReadMany']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'get';
		path: '-/servers/{serverId}/categories/{categoryId}/permissions/roles';
		parts: 6;
		params: undefined;
		response:
			operations['ChannelCategoryRolePermissionReadMany']['responses']['200'][
				'content'
			]['application/json'];
	}
	| {
		method: 'post';
		path: `/url-signatures`;
		parts: 1;
		params: operations['UrlSignatureCreateMany']['requestBody']['content'][
			'application/json'
		];
		response:
			operations['UrlSignatureCreateMany']['responses']['200']['content'][
				'application/json'
			];
	};
